Traceback (most recent call last):
  File "/home/runner/micromamba/envs/kerchunk-cookbook/lib/python3.13/site-packages/jupyter_core/utils/__init__.py", line 154, in wrapped
    asyncio.get_running_loop()
    ~~~~~~~~~~~~~~~~~~~~~~~~^^
RuntimeError: no running event loop

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/runner/micromamba/envs/kerchunk-cookbook/lib/python3.13/site-packages/jupyter_cache/executors/utils.py", line 58, in single_nb_execution
    executenb(
    ~~~~~~~~~^
        nb,
        ^^^
    ...<4 lines>...
        **kwargs,
        ^^^^^^^^^
    )
    ^
  File "/home/runner/micromamba/envs/kerchunk-cookbook/lib/python3.13/site-packages/nbclient/client.py", line 1319, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "/home/runner/micromamba/envs/kerchunk-cookbook/lib/python3.13/site-packages/jupyter_core/utils/__init__.py", line 158, in wrapped
    return loop.run_until_complete(inner)
           ~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^
  File "/home/runner/micromamba/envs/kerchunk-cookbook/lib/python3.13/asyncio/base_events.py", line 725, in run_until_complete
    return future.result()
           ~~~~~~~~~~~~~^^
  File "/home/runner/micromamba/envs/kerchunk-cookbook/lib/python3.13/site-packages/nbclient/client.py", line 709, in async_execute
    await self.async_execute_cell(
        cell, index, execution_count=self.code_cells_executed + 1
    )
  File "/home/runner/micromamba/envs/kerchunk-cookbook/lib/python3.13/site-packages/nbclient/client.py", line 1062, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/home/runner/micromamba/envs/kerchunk-cookbook/lib/python3.13/site-packages/nbclient/client.py", line 918, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
# We once again need to provide information for fsspec to access the remote file
storage_options = dict(
    remote_protocol="s3", remote_options=dict(anon=True), skip_instance_cache=True
)
# We will use the "kerchunk" engine in `xr.open_dataset` and pass the `storage_options` to the `kerchunk` engine through `backend_kwargs`
ds = xr.open_dataset(
    "single_file_kerchunk.json",
    engine="kerchunk",
    backend_kwargs={"storage_options": storage_options},
)
ds
------------------


[31m---------------------------------------------------------------------------[39m
[31mTypeError[39m                                 Traceback (most recent call last)
[36mCell[39m[36m [39m[32mIn[4][39m[32m, line 6[39m
[32m      2[39m storage_options = [38;5;28mdict[39m(
[32m      3[39m     remote_protocol=[33m"[39m[33ms3[39m[33m"[39m, remote_options=[38;5;28mdict[39m(anon=[38;5;28;01mTrue[39;00m), skip_instance_cache=[38;5;28;01mTrue[39;00m
[32m      4[39m )
[32m      5[39m [38;5;66;03m# We will use the "kerchunk" engine in `xr.open_dataset` and pass the `storage_options` to the `kerchunk` engine through `backend_kwargs`[39;00m
[32m----> [39m[32m6[39m ds = [43mxr[49m[43m.[49m[43mopen_dataset[49m[43m([49m
[32m      7[39m [43m    [49m[33;43m"[39;49m[33;43msingle_file_kerchunk.json[39;49m[33;43m"[39;49m[43m,[49m
[32m      8[39m [43m    [49m[43mengine[49m[43m=[49m[33;43m"[39;49m[33;43mkerchunk[39;49m[33;43m"[39;49m[43m,[49m
[32m      9[39m [43m    [49m[43mbackend_kwargs[49m[43m=[49m[43m{[49m[33;43m"[39;49m[33;43mstorage_options[39;49m[33;43m"[39;49m[43m:[49m[43m [49m[43mstorage_options[49m[43m}[49m[43m,[49m
[32m     10[39m [43m)[49m
[32m     11[39m ds

[36mFile [39m[32m~/micromamba/envs/kerchunk-cookbook/lib/python3.13/site-packages/xarray/backends/api.py:687[39m, in [36mopen_dataset[39m[34m(filename_or_obj, engine, chunks, cache, decode_cf, mask_and_scale, decode_times, decode_timedelta, use_cftime, concat_characters, decode_coords, drop_variables, inline_array, chunked_array_type, from_array_kwargs, backend_kwargs, **kwargs)[39m
[32m    675[39m decoders = _resolve_decoders_kwargs(
[32m    676[39m     decode_cf,
[32m    677[39m     open_backend_dataset_parameters=backend.open_dataset_parameters,
[32m   (...)[39m[32m    683[39m     decode_coords=decode_coords,
[32m    684[39m )
[32m    686[39m overwrite_encoded_chunks = kwargs.pop([33m"[39m[33moverwrite_encoded_chunks[39m[33m"[39m, [38;5;28;01mNone[39;00m)
[32m--> [39m[32m687[39m backend_ds = [43mbackend[49m[43m.[49m[43mopen_dataset[49m[43m([49m
[32m    688[39m [43m    [49m[43mfilename_or_obj[49m[43m,[49m
[32m    689[39m [43m    [49m[43mdrop_variables[49m[43m=[49m[43mdrop_variables[49m[43m,[49m
[32m    690[39m [43m    [49m[43m*[49m[43m*[49m[43mdecoders[49m[43m,[49m
[32m    691[39m [43m    [49m[43m*[49m[43m*[49m[43mkwargs[49m[43m,[49m
[32m    692[39m [43m[49m[43m)[49m
[32m    693[39m ds = _dataset_from_backend_dataset(
[32m    694[39m     backend_ds,
[32m    695[39m     filename_or_obj,
[32m   (...)[39m[32m    705[39m     **kwargs,
[32m    706[39m )
[32m    707[39m [38;5;28;01mreturn[39;00m ds

[36mFile [39m[32m~/micromamba/envs/kerchunk-cookbook/lib/python3.13/site-packages/kerchunk/xarray_backend.py:13[39m, in [36mKerchunkBackend.open_dataset[39m[34m(self, filename_or_obj, storage_options, open_dataset_options, **kw)[39m
[32m      9[39m [38;5;28;01mdef[39;00m[38;5;250m [39m[34mopen_dataset[39m(
[32m     10[39m     [38;5;28mself[39m, filename_or_obj, *, storage_options=[38;5;28;01mNone[39;00m, open_dataset_options=[38;5;28;01mNone[39;00m, **kw
[32m     11[39m ):
[32m     12[39m     open_dataset_options = (open_dataset_options [38;5;129;01mor[39;00m {}) | kw
[32m---> [39m[32m13[39m     ref_ds = [43mopen_reference_dataset[49m[43m([49m
[32m     14[39m [43m        [49m[43mfilename_or_obj[49m[43m,[49m
[32m     15[39m [43m        [49m[43mstorage_options[49m[43m=[49m[43mstorage_options[49m[43m,[49m
[32m     16[39m [43m        [49m[43mopen_dataset_options[49m[43m=[49m[43mopen_dataset_options[49m[43m,[49m
[32m     17[39m [43m    [49m[43m)[49m
[32m     18[39m     [38;5;28;01mreturn[39;00m ref_ds

[36mFile [39m[32m~/micromamba/envs/kerchunk-cookbook/lib/python3.13/site-packages/kerchunk/xarray_backend.py:45[39m, in [36mopen_reference_dataset[39m[34m(filename_or_obj, storage_options, open_dataset_options)[39m
[32m     42[39m [38;5;28;01mif[39;00m open_dataset_options [38;5;129;01mis[39;00m [38;5;28;01mNone[39;00m:
[32m     43[39m     open_dataset_options = {}
[32m---> [39m[32m45[39m store = [43mrefs_as_store[49m[43m([49m[43mfilename_or_obj[49m[43m,[49m[43m [49m[43m*[49m[43m*[49m[43mstorage_options[49m[43m)[49m
[32m     47[39m [38;5;28;01mreturn[39;00m xr.open_zarr(
[32m     48[39m     store, zarr_format=[32m2[39m, consolidated=[38;5;28;01mFalse[39;00m, **open_dataset_options
[32m     49[39m )

[31mTypeError[39m: refs_as_store() got an unexpected keyword argument 'skip_instance_cache'

